2018-03-11 20:23:36,791 ERROR: Exception on / [GET] [in /Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/wangzi/Desktop/my_guraduation_design/obm/app/main/routes.py", line 48, in index
    return render_template('index.html', title=_('Home'))
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/templating.py", line 85, in _get_source_fast
    raise TemplateNotFound(template)
TemplateNotFound: index.html
2018-03-11 20:24:18,851 INFO: Obm startup [in /Users/wangzi/Desktop/my_guraduation_design/obm/app/__init__.py:77]
2018-03-11 20:24:21,963 ERROR: Exception on / [GET] [in /Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/wangzi/Desktop/my_guraduation_design/obm/app/main/routes.py", line 48, in index
    return render_template('index.html', title=_('Home'))
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/wangzi/Desktop/my_guraduation_design/obm/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/Users/wangzi/Desktop/my_guraduation_design/obm/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 21, in block "body"
    {% block navbar %}
  File "/Users/wangzi/Desktop/my_guraduation_design/obm/app/templates/base.html", line 22, in block "navbar"
    <li><a href="{{ url_for('main.explore') }}">{{ _('Explore') }}</a></li>
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/werkzeug/routing.py", line 1768, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'main.explore'. Did you mean 'main.index' instead?
2018-03-11 20:25:59,947 ERROR: Exception on / [GET] [in /Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/wangzi/Desktop/my_guraduation_design/obm/app/main/routes.py", line 48, in index
    return render_template('index.html', title=_('Home'))
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/wangzi/Desktop/my_guraduation_design/obm/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/Users/wangzi/Desktop/my_guraduation_design/obm/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 21, in block "body"
    {% block navbar %}
  File "/Users/wangzi/Desktop/my_guraduation_design/obm/app/templates/base.html", line 22, in block "navbar"
    <li><a href="{{ url_for('main.index') }}">{{ _('Explore') }}</a></li>
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/werkzeug/routing.py", line 1768, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'main.explore'. Did you mean 'main.index' instead?
2018-03-11 20:26:04,593 INFO: Obm startup [in /Users/wangzi/Desktop/my_guraduation_design/obm/app/__init__.py:77]
